[pytest]
# Force le mode verbeux (-v) pour chaque exécution
addopts = -v

# Enregistrement de tes marqueurs
markers =
    fast: Maillon de tests rapides / smoke tests pour le pipeline de CI
    slow: Tests plus lourds nécessitant des calculs longs

# Filtre pour ignorer les alertes de dépréciation des packages tiers
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning